name: Tests
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"
    - name: Install `uv`
      run: curl -LsSf https://astral.sh/uv/install.sh | sh
    - name: Run tests
      run: uv run pytest
